packages:
  - client
  - service
  - service2
  - service3
  - service4

catalog:
  '@types/express': ^4.17.25
  '@types/js-yaml': ^4.0.9
  '@types/multer': 1.4.13
  '@types/node': ^20.19.27
  express: ^5.2.1
  js-yaml: ^4.1.0
  multer: 1.4.5-lts.2
  mysql2: 3.15.3
  sharp: 0.33.5
  tsx: ^4.21.0
  typescript: ~5.9.3
